### ISSUE TITLE
Problem with retriggering key events after JS breakpoint

### ISSUE THREAD

**Issue by mprinc** [RobertWHurst/KeyboardJS#105]
In the case we introduce a breakpoint in chrome dev tools that is inside the key event callback, the key event reoccurs.

If let, say we listen for CTRL+ENTER and we press this combo once and got at the breakpoint (dev tools opened) then we will trigger the same key event (and breakpoint) with ONLY and immediately after pressing the CTRL key WITHOUT pressing ENTER.

**Comment by RobertWHurst** [comment]
This is because the library thinks ctrl and enter are still pushed. When the break point was hit the browser fails to fire the keyup events for ctrl and enter once the JS is removed, thus there isn't a way to know the keys were released. This is a limitation of the semi-broken keyboard events in browsers.
