### ISSUE TITLE
Alt + key is being detected as Ctrl + alt + key 

### ISSUE THREAD

**Issue by Worie** [RobertWHurst/KeyboardJS#136]
When trying to type `alt+o` for example, library detects it as `ctrl+alt+o` instead of just only `alt+o`.

From what I've tested it happens only on Windows (I got reports of it not working on chrome, I don't have access to Windows at this point so I cannot investigate the issue more)

Works fine on Linux and OS X.

This is happening on version 2.3.4, tough - can anyone confirm that this not occurring in 2.4.1? As I said I have very limited testing capabilities, so if anyone can just leave a reply I'd be really glad, thanks in advance! 

Same thing is happening on the demo page: http://itsgreggreg.github.io/KeyboardJS/

**Comment by ToyYan** [comment]
I also have this problem, I just want to match the `f` key, but pressing `any + f` will be triggered.

**Comment by RobertWHurst** [comment]
I couldn't repo this one, unfortunately. But let me know if you're still having the issue with the latest version of the library.

@ToyYan In regards to your issue, that's actually by design. It mirrors the same behavior OS's flow. I'm thinking about adding an exclusive flag to combos though which would make it possible to clamp combos to only fire when no other keys are pressed. In any case, it's a different problem, but not a bad addition.
