### ISSUE TITLE
Sequence timing

### ISSUE THREAD

**Issue by tifDev** [RobertWHurst/KeyboardJS#144]
**Is it possible to increase the timing of a combination?** 
I have longer combinations on my web app like 'a r c g' or 'a r c g k' and they take a bit time to think & press.

**Comment by RobertWHurst** [comment]
Currently, the library doesn't support press and release, press and release sequences. At the moment all keys need to be pressed to trigger the combo, that said order can be enforced by using `>` instead of `+` between key names in the combo. Closing for now but please follow up if you'd still like help.
