### ISSUE TITLE
Make it easy to bind to "?"

### ISSUE THREAD

**Issue by jamesarosen** [RobertWHurst/KeyboardJS#5]
The only way to bind to `?` currently is to bind to "shift-slash," which only works on some keyboards. The trouble is that the only way to do a real binding to `?` is to use `onKeyPress`, instead of `onKeyUp`, which doesn't work in other cases. This is a known problem area for nearly all keybinding libraries. I'd love to hear your thoughts on how to do this elegantly.

**Comment by Prinzhorn** [comment]
I assume a lot has changed since 2012. I'm trying to get "?" working with a German keyboard layout

This does not get me anywhere, neither "ß" nor "shift + ß" work.

```js
keyboardJS._locale.bindKeyCode(223, ['ß']);
keyboardJS._locale.bindMacro('shift + ß', ['?']);

keyboardJS.bind('ß', console.log.bind(console, 'ß'));
keyboardJS.bind('shift + ?', console.log.bind(console, 'shift + ?'));
keyboardJS.bind('?', console.log.bind(console, '?'));
```

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/2560px-KB_Germany.svg)

Source: https://en.wikipedia.org/wiki/German_keyboard_layout

**Comment by daniel-wer** [comment]
@Prinzhorn In case you're still interested or for anyone else who stumbles upon this, the code snippet above did not work, because the `keyCode` for `ß` is actually 219.

Note, however, that there is a bug in the current keyboardJS version (see https://github.com/RobertWHurst/KeyboardJS/issues/164) which affects shortcuts using secondary key symbols (as `?`) which is why only the first of the three bindings works.

**Comment by Prinzhorn** [comment]
@daniel-wer I'm currently not using KeyboardJS in any project, but I might be in the future. Thanks for looking into this! How did you come up with 219? See screenshot, this is me hitting the "ß" button on this very GitHub page.

![Selection_820](https://user-images.githubusercontent.com/679144/108814647-77891380-75b3-11eb-9378-8e71248e818c.png)

**Comment by daniel-wer** [comment]
Unfortunately, keyboard events [are a mess](https://unixpapa.com/js/key.html) and the keyCode is different between keydown/keyup and keypress events, because they are different types of events. There is hope, though, in the form of [UI events](https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/) which should make all of this easier to work with.

If you use `document.addEventListener("keyup", e => console.log(e.which, e.keyCode, e.key))` you will get keyCode 219 for `ß` which seems to be what keyboardJS is using. In another issue I read that @RobertWHurst plans to switch to UI events, but I'm not sure whether any work in this direction has been done yet.

**Comment by Prinzhorn** [comment]
> If you use `document.addEventListener("keyup", e => console.log(e.which, e.keyCode, e.key))` you will get keyCode 219 for `ß`

Oh happy day :smile: 

![Selection_822](https://user-images.githubusercontent.com/679144/108823256-76121800-75c0-11eb-8c0c-3a27294c2c43.png)

This is Firefox. In Chromium it's indeed 219.
