### ISSUE TITLE
Keybinding combinations - action does not change when one (not both) keys is not lifted.

### ISSUE THREAD

**Issue by iamdevonbutler** [RobertWHurst/KeyboardJS#96]
So here's my issue:

I use command+right to switch tabs to the right and command+left to switch to tabs to the left. If I hold down command, press command+right things work as expected. But when I press command+left (while continuing to holding down the command key) the tab to the right is again selected. Things work fine when I lift up the command key in between actions.

**Comment by Prinzhorn** [comment]
I just wanted to create the exact same issue. In my case it's ctrl + z/y. I need to release ctrl every time. Which would drive my users crazy. Also holding ctrl+z does not trigger multiple events/repeats.

```js
keyboardjs.on('ctrl + z', this._handleUndo);
keyboardjs.on('ctrl + y', this._handleRedo);
```

**Comment by Prinzhorn** [comment]
Here's a workaround I'm now using, which hopefully does not have any side effects.

```js
var ctrlFilter = function(handler) {
	return function(e) {
		if(e.ctrlKey) {
			handler();
		}
	};
};

keyboardjs.on('z', ctrlFilter(this._handleUndo));
keyboardjs.on('y', ctrlFilter(this._handleRedo));
```

**Comment by jakecraige** [comment]
I'm also seeing this behavior with `command + +` and `command + -`

**Comment by RobertWHurst** [comment]
Seems to be a bug.

**Comment by daniel-wer** [comment]
I've done some investigation on this as we're hitting the very same issue, registering two bindings that use the command key (`command + z`, `command + y`).
This is actually happening, because [when the command key is kept pressed, `keyup` is not triggered for any other key](https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key). Unfortunately there seems to be no real workaround for this behaviour.
This causes keyboardjs' `pressedKeys` array to still contain `z` when pressing `command + z`, then releasing `z` only and pressing `y`, which is why the wrong callback is executed and only releasing `command` in between works as expected.

In my opinion this could be solved if the `_applyBindings` function would check whether the `keyCode` of the current `keydown` event is actually part of the `keyCombo` of the listener it wants to invoke.

If you agree @RobertWHurst I could create a PR for this. Or do you have a better idea?

**Comment by RobertWHurst** [comment]
@daniel-wer Please do. I'll have a look as soon as you post it.
